windows:
- geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAAAnwAAANcAAAAAAAAAAAAAAJ8AAABqQAAAAACAAAABaAAAAAAAAAA
    AAAAAnwAAANc
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2025-05-06T02:05:16'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Welcome to T3 Chat - T3 Chat
      url: https://t3.chat/chat/welcome
      zoom: 1.0
- geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAAAwwAAANcAAAAAAAAAAAAAAJ8AAABqgAAAAACAAAABaAAAAAAAAAA
    AAAAAwwAAANc
  tabs:
  - history:
    - active: true
      last_visited: '2025-05-06T02:05:13'
      original-url: https://codingchallenges.fyi/challenges/intro
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Coding Challenges - Intro | Coding Challenges
      url: https://codingchallenges.fyi/challenges/intro/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T02:05:19'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Catalog | CodeCrafters
      url: https://app.codecrafters.io/catalog
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T02:05:12'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Structure and Interpretation of Computer Programs, 2e: 1.2'
      url: http://sarabander.github.io/sicp/html/1_002e2.xhtml#g_t1_002e2
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T02:05:12'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 3.1 Introduction to Integers - Prealgebra 2e | OpenStax
      url: https://openstax.org/books/prealgebra-2e/pages/3-1-introduction-to-integers
      zoom: 1.0
  - active: true
    history:
    - active: true
      last_visited: '2025-05-06T02:05:12'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'Practical Design Patterns: Opaque Pointers and Objects in C | Interrupt'
      url: https://interrupt.memfault.com/blog/opaque-pointers
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T02:05:13'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Top Books By Month | Hacker News Books
      url: https://hackernewsbooks.com/archives
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T02:05:12'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Well-known tunes because of cracks/demos - Commodore 64 - Lemon64 - Commodore
        64
      url: https://www.lemon64.com/forum/viewtopic.php?t=85859
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T02:05:12'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: IntoIter - Learning Rust With Entirely Too Many Linked Lists
      url: https://rust-unofficial.github.io/too-many-lists/second-into-iter.html
      zoom: 1.0
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAABZ8AAAODAAAAAAAAAAAAAAMMAAADXAAAAAACBAAABaAAAAAAAAAA
    AAAABZ8AAAOD
  tabs:
  - history:
    - active: true
      last_visited: '2025-05-06T02:05:15'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: ncurses api - Google Zoeken
      url: https://www.google.nl/search?q=ncurses%20api
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T02:05:17'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: <curses.h>
      url: https://pubs.opengroup.org/onlinepubs/7908799/xcurses/curses.h.html
      zoom: 1.0
  - history:
    - last_visited: '2025-05-06T02:05:12'
      pinned: false
      title: Documentation - The Zig Programming Language
      url: https://ziglang.org/documentation/0.14.0/#catch
    - last_visited: '2025-05-06T05:53:10'
      pinned: false
      title: Documentation - The Zig Programming Language
      url: https://ziglang.org/documentation/0.14.0/#C-Type-Primitives
    - last_visited: '2025-05-06T05:53:24'
      pinned: false
      title: Documentation - The Zig Programming Language
      url: https://ziglang.org/documentation/0.14.0/#Values
    - last_visited: '2025-05-06T05:53:28'
      pinned: false
      title: Documentation - The Zig Programming Language
      url: https://ziglang.org/documentation/0.14.0/#Primitive-Types
    - last_visited: '2025-05-06T07:57:57'
      pinned: false
      title: Documentation - The Zig Programming Language
      url: https://ziglang.org/documentation/0.14.0/#String-Literals-and-Unicode-Code-Point-Literals
    - active: true
      last_visited: '2025-05-06T07:58:23'
      pinned: false
      scroll-pos:
        x: 0
        y: 35568
      title: Documentation - The Zig Programming Language
      url: https://ziglang.org/documentation/0.14.0/#Arrays
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T02:05:17'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: <curses.h>
      url: https://pubs.opengroup.org/onlinepubs/007908799/xcurses/curses.h.html
      zoom: 1.0
  - history:
    - last_visited: '2025-05-06T02:26:28'
      pinned: false
      title: ascii control codes - Google Zoeken
      url: https://www.google.nl/search?q=ascii%20control%20codes
    - active: true
      last_visited: '2025-05-06T02:26:30'
      pinned: false
      scroll-pos:
        x: 0
        y: 685
      title: ASCII control characters
      url: https://www.ascii-code.com/characters/control-characters
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T06:04:39'
      pinned: false
      scroll-pos:
        x: 0
        y: 805
      title: ncurses work with color - Google Zoeken
      url: https://www.google.nl/search?q=ncurses%20work%20with%20color
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T06:04:43'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Programming in Color with ncurses | Linux Journal
      url: https://www.linuxjournal.com/content/programming-color-ncurses#:~:text=In%20curses%20%2C%20you%20define%20colors,it%20to%20an%20index%20number.
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T06:04:47'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: About ncurses Colors | Linux Journal
      url: https://www.linuxjournal.com/content/about-ncurses-colors-0
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T06:04:52'
      pinned: false
      scroll-pos:
        x: 0
        y: 80
      title: Colors
      url: https://tldp.org/HOWTO/NCURSES-Programming-HOWTO/color.html
      zoom: 1.0
  - history:
    - last_visited: '2025-05-06T08:20:04'
      pinned: false
      title: immediate drawing mode - Google Zoeken
      url: https://www.google.nl/search?q=immediate%20drawing%20mode
    - active: true
      last_visited: '2025-05-06T22:17:43'
      pinned: false
      scroll-pos:
        x: 0
        y: 160
      title: immediate mode tutorial - Google Zoeken
      url: https://www.google.nl/search?q=immediate+mode+tutorial&sca_esv=e95a676e342dd0a3&sxsrf=AHTn8zq4i78EccbmhwMmYPSRusIgMfubSQ%3A1746508816995&ei=EJwZaNayPKbs7_UPpou6SQ&ved=0ahUKEwjW-oitjI6NAxUm9rsIHaaFLgkQ4dUDCBA&uact=5&oq=immediate+mode+tutorial&gs_lp=Egxnd3Mtd2l6LXNlcnAaAhgCIhdpbW1lZGlhdGUgbW9kZSB0dXRvcmlhbDIGEAAYFhgeMgYQABgWGB4yBRAAGO8FMggQABiABBiiBDIFEAAY7wUyBRAAGO8FMgUQABjvBUisR1CWGliHRHABeAGQAQCYAYUBoAHYCqoBBDE0LjO4AQPIAQD4AQGYAhKgAtELwgIKEAAYsAMY1gQYR8ICCBAAGAcYCBgewgIHECMYsAIYJ8ICBxAAGIAEGA3CAgYQABgNGB7CAgYQABgHGB7CAgoQIxiABBgnGIoFwgIIEAAYgAQYywHCAgsQABiABBjLARiLA8ICCBAAGBYYChgemAMAiAYBkAYIkgcEMTQuNKAHnluyBwQxMy40uAfDCw&sclient=gws-wiz-serp
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T22:17:52'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: 'I made a tutorial video about immediate mode GUI : r/C_Programming'
      url: https://www.reddit.com/r/C_Programming/comments/1gamtnc/i_made_a_tutorial_video_about_immediate_mode_gui/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T22:19:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: (693) Dead Simple GUI (Immediate Mode) - YouTube
      url: https://www.youtube.com/watch?v=go-h9c_h6Uw
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-06T08:20:10'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Immediate mode (computer graphics) - Wikipedia
      url: https://en.wikipedia.org/wiki/Immediate_mode_(computer_graphics)
      zoom: 1.0
  - history:
    - last_visited: '2025-05-06T08:30:56'
      pinned: false
      title: Immediate mode (computer graphics) - Wikipedia
      url: https://en.wikipedia.org/wiki/Immediate_mode_(computer_graphics)#cite_ref-7
    - active: true
      last_visited: '2025-05-06T08:31:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 1361
      title: Immediate-Mode Graphical User Interfaces (2005)
      url: https://caseymuratori.com/blog_0001
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-07T00:36:24'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Computer, Enhance! | Casey Muratori | Substack
      url: https://www.computerenhance.com/
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-07T00:36:24'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Table of Contents - by Casey Muratori - Computer, Enhance!
      url: https://www.computerenhance.com/p/table-of-contents
      zoom: 1.0
  - active: true
    history:
    - last_visited: '2025-05-07T00:30:18'
      pinned: false
      title: ncurses update scree - Google Zoeken
      url: https://www.google.nl/search?q=ncurses%20update%20scree
    - last_visited: '2025-05-07T00:36:23'
      pinned: false
      title: ncurses update screen - Google Zoeken
      url: https://www.google.nl/search?q=ncurses+update+screen&sca_esv=e4a529db535589d2&sxsrf=AHTn8zpZpi9DpEsRdtHgK5HzFErf5gm4jA%3A1746567031210&ei=d38aaLvODPzo7_UPkcaPyAc&ved=0ahUKEwj75eKb5Y-NAxV89LsIHRHjA3kQ4dUDCBA&uact=5&oq=ncurses+update+screen&gs_lp=Egxnd3Mtd2l6LXNlcnAiFW5jdXJzZXMgdXBkYXRlIHNjcmVlbjILEAAYgAQYsAMYogQyCBAAGLADGO8FMgsQABiABBiwAxiiBEiLCFAAWABwAHgAkAEAmAE4oAE4qgEBMbgBA8gBAPgBAZgCAaACQZgDAOIDBRIBMSBAiAYBkAYDkgcBMaAHgQKyBwExuAdB&sclient=gws-wiz-serp
    - last_visited: '2025-05-07T00:56:57'
      pinned: false
      title: ncurses refresh order - Google Zoeken
      url: https://www.google.nl/search?q=ncurses+refresh+order&sca_esv=e4a529db535589d2&sxsrf=AHTn8zqxejpEl4cydB6Yd-E0S4Guf7m5fg%3A1746567324223&ei=nIAaaOSvDf_r7_UP5pzm0AI&ved=0ahUKEwjk7b6n5o-NAxX_9bsIHWaOGSoQ4dUDCBA&uact=5&oq=ncurses+refresh+order&gs_lp=Egxnd3Mtd2l6LXNlcnAaAhgCIhVuY3Vyc2VzIHJlZnJlc2ggb3JkZXIyBRAhGKABSPU3UIkBWIQ2cAN4AJABAJgBU6ABhA6qAQIyOLgBA8gBAPgBAZgCGaAClAzCAgsQABiABBiwAxiiBMICCBAAGLADGO8FwgIEECMYJ8ICCBAAGIAEGKIEwgIFEAAY7wXCAgYQABgWGB7CAggQABiABBjLAcICCBAAGBYYChgewgIKECMYgAQYJxiKBcICDBAjGIAEGBMYJxiKBcICBRAAGIAEwgILEAAYgAQYywEYiwPCAgkQABiABBgTGA3CAggQABgTGA0YHsICChAAGBMYCBgNGB7CAgQQIRgVmAMAiAYBkAYDkgcCMjWgB9x1sgcCMjK4B_wL&sclient=gws-wiz-serp
    - active: true
      last_visited: '2025-05-07T00:57:02'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: '(693) Ncurses Tutorial 9 - Refreshing: "When" and "Why" - YouTube'
      url: https://www.youtube.com/watch?v=U82JXzJoCL4
      zoom: 1.0
  - history:
    - active: true
      last_visited: '2025-05-07T00:49:47'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: NCURSES Programming HOWTO
      url: https://invisible-island.net/ncurses/howto/NCURSES-Programming-HOWTO.html
      zoom: 1.0
